volumes:
  git_repo: {}

x-default-os-configuration:
  &default-os-configuration
  command: tail -f /dev/null
  user: docker
  volumes:
    - ./ci_test.sh:/ci_test.sh:rxo
  depends_on:
    - file-server

services:
  debian:
    <<: *default-os-configuration
    build:
      context: .
      args:
        OS_NAME: debian
      dockerfile: Dockerfile
      target: os
  ubuntu:
    <<: *default-os-configuration
    build:
      context: .
      args:
        OS_NAME: ubuntu
      dockerfile: Dockerfile
      target: os
  fedora:
    <<: *default-os-configuration
    build:
      context: .
      args:
        OS_NAME: fedora
      dockerfile: Dockerfile
      target: os
  # Mock git repo
  git-tool:
    image: bitnami/git:latest
    command:
      - /bin/sh
      - -c
      - |
        # Remove status file
        if [ -f "/git_repo/status" ]; then
          rm -f /git_repo/status
        fi

        # Remove git repo
        if [ -d "/git_repo/myenv.git" ]; then
          rm -rf /git_repo/myenv.git
        fi

        # Remove /git_repo/myenv.raw
        if [ -d "/git_repo/myenv.raw" ]; then
          rm -rf /git_repo/myenv.raw
        fi

        # Copy to a new local_repo (/git_repo/myenv.raw)
        cp -a /local_repo/ /git_repo/myenv.raw
        # fatal: detected dubious ownership in repository at '/git_repo/myenv.raw'
        # To add an exception for this directory, call:
        git config --global --add safe.directory /git_repo/myenv.raw
        # Apply new changes
        git -C /git_repo/myenv.raw add .
        git -C /git_repo/myenv.raw commit -m "new_changes"
        
        # Setup git repo
        if git clone --bare /git_repo/myenv.raw /git_repo/myenv.git; then
          if cp -Rf /git_repo/myenv.raw/.git /git_repo/myenv.git; then
            if git -C /git_repo/myenv.git --bare update-server-info; then
              echo "ok" > /git_repo/status
            fi
          fi
        fi
        
    volumes:
      - ./:/local_repo:ro
      - git_repo:/git_repo
  # Serve file-server and git repo
  file-server:
    image: caddy
    volumes:
      - ./:/local_repo/files:ro
      - git_repo:/local_repo/vleedev:ro
    command: caddy file-server --browse --root /local_repo
    depends_on:
      - git-tool
