volumes:
  git_repo: {}

x-default-os-configuration:
  &default-os-configuration
  command: tail -f /dev/null
  user: docker
  volumes:
    - ./ci_test.sh:/ci_test.sh:rxo
  depends_on:
    - file-server

services:
  debian:
    <<: *default-os-configuration
    build:
      context: .
      args:
        OS_NAME: debian
      dockerfile: Dockerfile
      target: os
  ubuntu:
    <<: *default-os-configuration
    build:
      context: .
      args:
        OS_NAME: ubuntu
      dockerfile: Dockerfile
      target: os
  fedora:
    <<: *default-os-configuration
    build:
      context: .
      args:
        OS_NAME: fedora
      dockerfile: Dockerfile
      target: os
  # Mock git repo
  git-tool:
    image: bitnami/git:latest
    command:
      - /bin/sh
      - -c
      - |
        rm -rf /git_repo/myenv.git
        git clone --bare /local_repo /git_repo/myenv.git
        cp -Rf /local_repo/.git /git_repo/myenv.git
        cd /git_repo/myenv.git && git --bare update-server-info
    volumes:
      - ./:/local_repo:ro
      - git_repo:/git_repo
  # Serve file-server and git repo
  file-server:
    image: caddy
    volumes:
      - ./:/local_repo/files:ro
      - git_repo:/local_repo/vleedev:ro
    command: caddy file-server --browse --root /local_repo
    depends_on:
      - git-tool
