version: '3'
services:
  gcli:
    # This is the environment for google cloud cli (gcloud command)
    # To initialize the gcloud CLI, run `gcloud init`
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:389.0.0-debian_component_based
    command:
      - sleep
      - infinity
    user: root
  debian-bullseye: # Debian 11
    image: debian:bullseye
    command:
      - sleep
      - infinity
    user: root
  debian-buster: # Debian 10
    image: debian:buster
    command:
      - sleep
      - infinity
    user: root
  debian-stretch: # Debian 9
    image: debian:stretch
    command:
      - sleep
      - infinity
    user: root
  debian-jessie: # Debian 8
    image: debian:jessie
    command:
      - sleep
      - infinity
    user: root
  debian-wheezy: # Debian 7
    image: debian:wheezy
    command:
      - sleep
      - infinity
    user: root
  ubuntu-focal: # ubuntu 20.04 LTS
    image: ubuntu:focal
    command:
      - sleep
      - infinity
    user: root
  ubuntu-bionic: # ubuntu 18.04 LTS
    image: ubuntu:bionic
    command:
      - sleep
      - infinity
    user: root
  ubuntu-xenial: # ubuntu 16.04 LTS
    image: ubuntu:xenial
    command:
      - sleep
      - infinity
    user: root
  ubuntu-trusty: # ubuntu 14.04 LTS
    image: ubuntu:trusty
    command:
      - sleep
      - infinity
    user: root
  ## Centos
  centos-7:
    image: centos:centos7
    command:
      - sleep
      - infinity
    user: root
    