version: '3.9'
# Extension fields
# Refer: https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields
x-default-container-configuration:
  &default-container-configuration
  command:
    - sleep
    - infinity
  user: root
services:
  gcli:
    # This is the environment for google cloud cli (gcloud command)
    # To initialize the gcloud CLI, run `gcloud init`
    << : *default-container-configuration
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:389.0.0-debian_component_based
  # Debian environment
  debian: # Debian latest
    <<: *default-container-configuration
    image: debian:latest
  debian-bullseye: # Debian 11
    << : *default-container-configuration
    image: debian:bullseye
  debian-buster: # Debian 10
    << : *default-container-configuration
    image: debian:buster
  debian-stretch: # Debian 9
    << : *default-container-configuration
    image: debian:stretch
  debian-jessie: # Debian 8
    << : *default-container-configuration
    image: debian:jessie
  debian-wheezy: # Debian 7
    << : *default-container-configuration
    image: debian:wheezy
  # Ubuntu environment
  ubuntu: # Ubuntu latest
    <<: *default-container-configuration
    image: ubuntu:latest
  ubuntu-focal: # ubuntu 20.04 LTS
    << : *default-container-configuration
    image: ubuntu:focal
  ubuntu-bionic: # ubuntu 18.04 LTS
    << : *default-container-configuration
    image: ubuntu:bionic
  ubuntu-xenial: # ubuntu 16.04 LTS
    << : *default-container-configuration
    image: ubuntu:xenial
  ubuntu-trusty: # ubuntu 14.04 LTS
    << : *default-container-configuration
    image: ubuntu:trusty
  ## Centos environment
  centos: # Centos latest
    <<: *default-container-configuration
    image: centos:latest
  centos-7:
    << : *default-container-configuration
    image: centos:centos7
  ## Alpine environment
  alpine: # Alpine latest
    <<: *default-container-configuration
    image: alpine:latest
  alpine-3.16: # Alpine 3.16
    <<: *default-container-configuration
    image: alpine:3.16
    