name: Integration Testing

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Integration_Test:
    strategy:
      matrix:
        environment: [ debian, ubuntu, fedora ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run test for ${{ matrix.environment }}
        run: ./test.local.sh ${{ matrix.environment }}
